### ISSUE TITLE
fails with 'Malformed version' when constraint syntax used

### ISSUE THREAD

**Issue by elmariofredo** [dirien/tfu#12]
Hi, great tool! 

Unfortunately it fails when constraint syntax used https://www.terraform.io/docs/language/expressions/version-constraints.html#version-constraint-syntax

When you try to run it on:

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.47"
    }
  }
}
```

It will return:

```bash
🔴 GIT_TOKEN not set, skipping private module checks
🔎 Start scanning for TF providers...  ⣟ Malformed version: ~> 3.47
```

It also seems it crash and stop processing other files.

**Comment by dirien** [comment]
Hi @elmariofredo, released a new version of tfu. This will address this issue. Updating only =x.y.z or x.y.z entries but keep the rest untouched. Thx for the feedback!

**Comment by elmariofredo** [comment]
Great thanks! 🙂
