### ISSUE TITLE
getting "Malformed version" when running `tfu`

### ISSUE THREAD

**Issue by pdemagny** [dirien/tfu#2]
Hi,

Given the following `versions.tf` file:

```hcl
terraform {
  required_version = "= 1.0.0"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "= 3.71.0"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "= 3.71.0"
    }
    mongodbatlas = {
      source  = "mongodb/mongodbatlas"
      version = "= 0.9.1"
    }
    ovh = {
      source  = "ovh/ovh"
      version = "= 0.13.0"
    }
  }
}
```

I get these results (even without the --dry-run argument):

```bash
❯ tfu update -d . --dry-run

🔎 Start scanning for TF providers...  ⢿ Malformed version: = 3.71.0
```

And

```bash
❯ tfu update -f versions.tf --dry-run

🔎 Start scanning for TF providers...  ⢿ Malformed version: = 3.71.0
```

I am using Version: 0.1.0, Git Commit: 3e42fb2337856c33823dba3f9fa901020f7eafc5, on Debian 10.

Am i doing something wrong ?

**Comment by dirien** [comment]
Hi @pdemagny,

thanks for the feedback. `tfu` is not checking for the version constraint syntax.

if you like me and always want a fix version you need to remove the `=`in the version. As you dont neet the equal sign on exact version. After this `tfu` is working fine.

> = (or no operator): Allows only one exact version number. Cannot be combined with other conditions.

https://www.terraform.io/docs/language/expressions/version-constraints.html#version-constraint-syntax

**Comment by pdemagny** [comment]
Indeed this is working, i'll do that, thanks ;)
